FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
ENV CGO_ENABLED=0 GOOS=linux
RUN go build -ldflags="-w -s" -o ./api ./cmd/api

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/api /app/api
RUN chmod +x /app/api 
EXPOSE 8080
CMD ["./api"]